---
title: "data wrangling i"
author: "Leighanne Wang"
date: "9/22/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

# Read in some data

Read in the litters dataset.
```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Take a look at the data
```{r}
litters_df
```

```{r}
tail(litters_df) #gives you the last 6 rows, 'head' would give first 6
```

```{r}
skimr::skim(litters_df)
# you can use view(litters_df) to view but it opens up a new window, so try and use in the console only not hte r markdown file
```

## Options to read_scv

check out '?read_csv()' for more information
```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv", skip = 10, col_names = FALSE)
```

## Other file formats

Read in excel files

```{r}
mlb_df = read_excel("./data_import_examples/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in SAS files
```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison with Base R
```{r}
litters_base = read.csv("data_import_examples/FAS_litters.csv")
litters_readr = read_csv("data_import_examples/FAS_litters.csv")

litters_base
litters_readr

#use readr because base is just too cumbersome 
```


