---
title: "data manipulation"
author: "Leighanne Wang"
date: "9/22/2020"
output: github_document
---

```{r setup}
library(tidyverse)
```
## Load in FAS litters data

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## 'select'

Choose some columns and not others

```{r}
select(litters_df, group, litter_number)
```

```{r}
select(litters_df, group:litter_number)
```

```{r}
select(litters_df, -litter_number) #remove litter number column
```

Renaming columns

```{r}
select(litters_df, GROUP = group) #rename group to GROUP
```

```{r}
rename(litters_df, GROUP = group)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))
```

```{r}
#relocate a column to the first column area
select(litters_df, litter_number, everything())
relocate(litters_df, litter_number)
```

## 'filter'

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20)) #can also do != 20
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8"))
```

## 'mutate'

```{r}
mutate( #can conain multiple functions
  litters_df, 
  wt_gain = gd18_weight - gd0_weight, # create a new variable
  group = str_to_lower(group)) # change name of variable group
```

## 'arrange'

```{r}
arrange(litters_df, pups_born_alive) # does it in ascending order
```

```{r}
arrange(litters_df, pups_born_alive, gd0_weight) #ascending order of pups born alive and then within that, ascending order of gd0 weight
```

## '%>%'

```{r}
litters_data_row = read_csv("./data_import_examples/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_row)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

--> Use pipe operator instead!

```{r}
litters_df = 
  read_csv("./data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
```






