---
title: "tidy data"
author: "Leighanne Wang"
date: "9/22/2020"
output: github_document
---

```{r setup}
library(tidyverse)
```

## 'pivot_longer'

```{r}
pulse_data =
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Wide Format to long format

```{r}
pulse_data_tidy =
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score",
    values_to = "bdi"
  )
```

rewrite, combine, and extend (to add a mutate)
```{r}
pulse_data =
  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
```

## 'pivot_wider'

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

#take the 'tidy' data and 'untidy' it for a publication

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = mean
  )
```


## Binding rows

Using LoTR data

First step: import each table

```{r}
fellowship_ring =
  readxl::read_excel("./data_import_examples/LoTR_words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers =
  readxl::read_excel("./data_import_examples/LoTR_words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king =
  readxl::read_excel("./data_import_examples/LoTR_words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")
```

Bind all rows together

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```

